Add Elasticsearch index templates
salt-formulas/salt-formula-elasticsearch pull request #10
Opened 2016-11-17 15:02 UTC by thouveng

This patch adds three index templates that are used by StackLight.

2016-11-17 16:22 UTC, simonpasquier approved these changes

2016-11-17 16:41 UTC, SwannCroiset requested changes

2016-11-17 16:41 UTC, SwannCroiset commented on elasticsearch/files/es_template_kibana4.json
> +    "template": "Kibana4"
"template" must be a pattern matching the name of indices. like log-*
here the template is ".kibana"

2016-11-17 16:41 UTC, SwannCroiset commented on elasticsearch/files/es_template_log.json
> +    "template": "Logs"
log-*

2016-11-17 16:41 UTC, SwannCroiset commented on elasticsearch/files/es_template_notification.json
> +    "template": "Notifications"
notification-*

2016-11-18 13:34 UTC, thouveng commented
I have updated the review and added the possibility to delete an index.

2016-11-18 14:12 UTC, elemoine approved these changes

2016-11-18 16:25 UTC, simonpasquier approved these changes

2016-11-21 09:06 UTC, SwannCroiset approved these changes

2016-11-21 09:07 UTC, merged