Enable script supporting in request
salt-formulas/salt-formula-elasticsearch pull request #26
Opened 2016-12-21 10:04 UTC by ityaptin

This feature is needed for resources updating in Telemetry

2016-12-21 10:04 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2016-12-21 10:11 UTC, simonpasquier requested changes

2016-12-21 10:11 UTC, simonpasquier commented on metadata/service/server/cluster.yml
> +      enable_script: true
you shouldn't change the previous setting. Please modify the user model instead.

2016-12-21 10:11 UTC, simonpasquier commented on elasticsearch/files/elasticsearch.yml
> +  inline: on
Can you try to be less permissive and enable only the required extensions? See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html.

2016-12-22 15:15 UTC, SwannCroiset requested changes

2016-12-22 15:15 UTC, SwannCroiset commented on elasticsearch/files/elasticsearch.yml
> +script: {{ server.script }}
you must serialize the dict to yaml : 

`{{ server.script|yaml }}`

2016-12-27 16:00 UTC, simonpasquier approved these changes

2016-12-27 16:01 UTC, merged